{% set name = "avahi" %}
{% set version = "0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://avahi.org/download/{{ name }}-{{ version }}.tar.gz
  sha256: 060309d7a333d38d951bc27598c677af1796934dbd98e1024e7ad8de798fedda
  patches:
    - patches/0001-move-avahi-runtime-dir-to-prefix.patch
    - patches/0002-use-mac-macro-autoipd.patch

build:
  number: 1
  skip: true  # [win]

outputs:
  - name: python-avahi
    script: python-avahi.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - intltool
        - make
        - pkg-config
      host:
        - dbus >=0.34
        - dbus-python >=0.34
        - expat
        - pygobject
        - python
      run:
        - dbus-python >=0.34
        - pygobject
        - python
    test:
      imports:
        - avahi
      commands:
        # check script
        - avahi-bookmarks --help
    about:
      home: http://avahi.org
      dev_url: https://github.com/lathiat/avahi.git
      doc_url: http://avahi.org/doxygen/html/
      license: LGPL-2.1-or-later
      license_file: LICENSE
      summary: Python utility package for Avahi
      description: |
        Avahi is a system which facilitates service discovery on
        a local network -- this means that you can plug your laptop or
        computer into a network and instantly be able to view other people who
        you can chat with, find printers to print to or find files being
        shared. This kind of technology is already found in MacOS X (branded
        'Rendezvous', 'Bonjour' and sometimes 'ZeroConf') and is very
        convenient.

        This package contains utility modules to talk to Avahi with Python easier.
  - name: avahi
    script: lib-avahi.sh
    requirements:
      build:
        # If your project compiles code (such as a C extension) then add the required compilers as separate entries here.
        # Compilers are named 'c', 'cxx' and 'fortran'.
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - make
        - pkg-config
        - intltool
        - make
      host:
        - libevent
        - libdaemon
        - dbus >=0.34
    test:
      requires:
        - dbus >=0.34
        - libdaemon
        - libevent
      commands:
        - avahi-browse --version
        - avahi-publish --version
        - avahi-resolve --version

about:
  home: http://avahi.org
  dev_url: https://github.com/lathiat/avahi.git
  doc_url: http://avahi.org/doxygen/html/
  license: LGPL-2.1-or-later
  license_file: LICENSE
  summary: Local network service discovery
  description: |
    Avahi is a system which facilitates service discovery on
    a local network -- this means that you can plug your laptop or
    computer into a network and instantly be able to view other people who
    you can chat with, find printers to print to or find files being
    shared. This kind of technology is already found in MacOS X (branded
    'Rendezvous', 'Bonjour' and sometimes 'ZeroConf') and is very
    convenient.

extra:
  recipe-maintainers:
    - andfoy
    - duncanmmacleod
