# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "uUUH8HGE9218DP5tcYdZm8QqSciZ7Y4rrt5V2jEEIrBhnEPBF4LmdOVLnVMbYcBlbcJCRyjfLdQoO84sMhhh151hkBP6RB1jHEDS3e3RVrA1sVn/icKok2+RDltTVytwvFkOUcybzwo0NWoSjiAHLirgkwjA0xzcJ0cTLCHborsqsnhHqPZyHvfSdSDQ4idwaNfU0cMNfucoOxRJG3EyhehTyXDIbfYIKyKXUt8e/ivN2L78QzPadLJMlrjU8FvUaeqgePbTLoTGbBdJ0ok3zXiv/hLjrCRax8wKGViYtPhim0p+OHd+FAN2QIVROGu8UQQS7T1/iS4Y64Q6jMMx4PxFoeBODJ9ryqsB+LZZQ5glRwUKG6HDu+rh9SxMU86lxoCi3h3cjqJ9cov8oDPRBgSFlW+qcyqbAPnVGTR88ULmvfji1gsmYY0TKIJZqm9yk2Ay+7WwNXEqjT8b7nfo0tRbZrQXaYA/VarpYoDkACeT2yXPjdtiutAHw/Qmw0DH8UfM9Sd0h9SpFDbgVvCV4V1zV63CPnBT2ZBFSqu8MoECy5i700q0xmDX/WBDVsYA7cBhVfkKFtMza1PHQaTnDG0mJ7ocl5mGtsH8rGhH6xJnEdglTKoQuCAoTKrpw8fg42RKwbAznTEnJxwbBr8cTIbEtuVuxNdNjAlMAfN80Q0="

matrix:
  include:
    - env: CONFIG=linux_ppc64le_ UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le
      dist: focal

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"
  - export FEEDSTOCK_NAME=$(basename ${TRAVIS_REPO_SLUG})
  - if [[ "${TRAVIS_PULL_REQUEST:-}" == "false" ]]; then export IS_PR_BUILD="False"; else export IS_PR_BUILD="True"; fi


  - if [[ ${PLATFORM} =~ .*linux.* ]]; then CONDA_FORGE_DOCKER_RUN_ARGS="--network=host --security-opt=seccomp=unconfined" ./.scripts/run_docker_build.sh; fi